//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TugboatDBModel", "FK_ClientWeek_Client", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Tugboat.Client), "ClientWeek", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Tugboat.ClientWeek), true)]
[assembly: EdmRelationshipAttribute("TugboatDBModel", "FK_Time_Student", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Tugboat.Student), "Time", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Tugboat.Time), true)]
[assembly: EdmRelationshipAttribute("TugboatDBModel", "FK_ClientWeek_Week", "Week", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Tugboat.Week), "ClientWeek", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Tugboat.ClientWeek), true)]
[assembly: EdmRelationshipAttribute("TugboatDBModel", "FK_Time_ClientWeek", "ClientWeek", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Tugboat.ClientWeek), "Time", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Tugboat.Time), true)]

#endregion

namespace Tugboat
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TugboatDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TugboatDBEntities object using the connection string found in the 'TugboatDBEntities' section of the application configuration file.
        /// </summary>
        public TugboatDBEntities() : base("name=TugboatDBEntities", "TugboatDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TugboatDBEntities object.
        /// </summary>
        public TugboatDBEntities(string connectionString) : base(connectionString, "TugboatDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TugboatDBEntities object.
        /// </summary>
        public TugboatDBEntities(EntityConnection connection) : base(connection, "TugboatDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Clients
        {
            get
            {
                if ((_Clients == null))
                {
                    _Clients = base.CreateObjectSet<Client>("Clients");
                }
                return _Clients;
            }
        }
        private ObjectSet<Client> _Clients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClientWeek> ClientWeeks
        {
            get
            {
                if ((_ClientWeeks == null))
                {
                    _ClientWeeks = base.CreateObjectSet<ClientWeek>("ClientWeeks");
                }
                return _ClientWeeks;
            }
        }
        private ObjectSet<ClientWeek> _ClientWeeks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Time> Times
        {
            get
            {
                if ((_Times == null))
                {
                    _Times = base.CreateObjectSet<Time>("Times");
                }
                return _Times;
            }
        }
        private ObjectSet<Time> _Times;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Week> Weeks
        {
            get
            {
                if ((_Weeks == null))
                {
                    _Weeks = base.CreateObjectSet<Week>("Weeks");
                }
                return _Weeks;
            }
        }
        private ObjectSet<Week> _Weeks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClients(Client client)
        {
            base.AddObject("Clients", client);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClientWeeks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientWeeks(ClientWeek clientWeek)
        {
            base.AddObject("ClientWeeks", clientWeek);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Times EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTimes(Time time)
        {
            base.AddObject("Times", time);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Weeks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeeks(Week week)
        {
            base.AddObject("Weeks", week);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TugboatDBModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="clientGuid">Initial value of the ClientGuid property.</param>
        /// <param name="clientName">Initial value of the ClientName property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="dateModified">Initial value of the DateModified property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="modifiedBy">Initial value of the ModifiedBy property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        public static Client CreateClient(global::System.Int32 clientId, global::System.Guid clientGuid, global::System.String clientName, global::System.DateTime dateCreated, global::System.DateTime dateModified, global::System.String createdBy, global::System.String modifiedBy, global::System.Boolean active)
        {
            Client client = new Client();
            client.ClientId = clientId;
            client.ClientGuid = clientGuid;
            client.ClientName = clientName;
            client.DateCreated = dateCreated;
            client.DateModified = dateModified;
            client.CreatedBy = createdBy;
            client.ModifiedBy = modifiedBy;
            client.Active = active;
            return client;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                if (_ClientId != value)
                {
                    OnClientIdChanging(value);
                    ReportPropertyChanging("ClientId");
                    _ClientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClientId");
                    OnClientIdChanged();
                }
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ClientGuid
        {
            get
            {
                return _ClientGuid;
            }
            set
            {
                OnClientGuidChanging(value);
                ReportPropertyChanging("ClientGuid");
                _ClientGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientGuid");
                OnClientGuidChanged();
            }
        }
        private global::System.Guid _ClientGuid;
        partial void OnClientGuidChanging(global::System.Guid value);
        partial void OnClientGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TugboatDBModel", "FK_ClientWeek_Client", "ClientWeek")]
        public EntityCollection<ClientWeek> ClientWeeks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClientWeek>("TugboatDBModel.FK_ClientWeek_Client", "ClientWeek");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClientWeek>("TugboatDBModel.FK_ClientWeek_Client", "ClientWeek", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TugboatDBModel", Name="ClientWeek")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClientWeek : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClientWeek object.
        /// </summary>
        /// <param name="clientWeekId">Initial value of the ClientWeekId property.</param>
        /// <param name="clientWeekGuid">Initial value of the ClientWeekGuid property.</param>
        /// <param name="weekId">Initial value of the WeekId property.</param>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="dateModified">Initial value of the DateModified property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="modifiedBy">Initial value of the ModifiedBy property.</param>
        /// <param name="clientApproved">Initial value of the ClientApproved property.</param>
        /// <param name="approved">Initial value of the Approved property.</param>
        public static ClientWeek CreateClientWeek(global::System.Int32 clientWeekId, global::System.Guid clientWeekGuid, global::System.Int32 weekId, global::System.Int32 clientId, global::System.DateTime dateCreated, global::System.DateTime dateModified, global::System.String createdBy, global::System.String modifiedBy, global::System.Boolean clientApproved, global::System.Boolean approved)
        {
            ClientWeek clientWeek = new ClientWeek();
            clientWeek.ClientWeekId = clientWeekId;
            clientWeek.ClientWeekGuid = clientWeekGuid;
            clientWeek.WeekId = weekId;
            clientWeek.ClientId = clientId;
            clientWeek.DateCreated = dateCreated;
            clientWeek.DateModified = dateModified;
            clientWeek.CreatedBy = createdBy;
            clientWeek.ModifiedBy = modifiedBy;
            clientWeek.ClientApproved = clientApproved;
            clientWeek.Approved = approved;
            return clientWeek;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientWeekId
        {
            get
            {
                return _ClientWeekId;
            }
            set
            {
                if (_ClientWeekId != value)
                {
                    OnClientWeekIdChanging(value);
                    ReportPropertyChanging("ClientWeekId");
                    _ClientWeekId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClientWeekId");
                    OnClientWeekIdChanged();
                }
            }
        }
        private global::System.Int32 _ClientWeekId;
        partial void OnClientWeekIdChanging(global::System.Int32 value);
        partial void OnClientWeekIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ClientWeekGuid
        {
            get
            {
                return _ClientWeekGuid;
            }
            set
            {
                OnClientWeekGuidChanging(value);
                ReportPropertyChanging("ClientWeekGuid");
                _ClientWeekGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientWeekGuid");
                OnClientWeekGuidChanged();
            }
        }
        private global::System.Guid _ClientWeekGuid;
        partial void OnClientWeekGuidChanging(global::System.Guid value);
        partial void OnClientWeekGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WeekId
        {
            get
            {
                return _WeekId;
            }
            set
            {
                OnWeekIdChanging(value);
                ReportPropertyChanging("WeekId");
                _WeekId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WeekId");
                OnWeekIdChanged();
            }
        }
        private global::System.Int32 _WeekId;
        partial void OnWeekIdChanging(global::System.Int32 value);
        partial void OnWeekIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                OnClientIdChanging(value);
                ReportPropertyChanging("ClientId");
                _ClientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientId");
                OnClientIdChanged();
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypeOfWork
        {
            get
            {
                return _TypeOfWork;
            }
            set
            {
                OnTypeOfWorkChanging(value);
                ReportPropertyChanging("TypeOfWork");
                _TypeOfWork = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TypeOfWork");
                OnTypeOfWorkChanged();
            }
        }
        private global::System.String _TypeOfWork;
        partial void OnTypeOfWorkChanging(global::System.String value);
        partial void OnTypeOfWorkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ClientApproved
        {
            get
            {
                return _ClientApproved;
            }
            set
            {
                OnClientApprovedChanging(value);
                ReportPropertyChanging("ClientApproved");
                _ClientApproved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientApproved");
                OnClientApprovedChanged();
            }
        }
        private global::System.Boolean _ClientApproved;
        partial void OnClientApprovedChanging(global::System.Boolean value);
        partial void OnClientApprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateClientApproved
        {
            get
            {
                return _DateClientApproved;
            }
            set
            {
                OnDateClientApprovedChanging(value);
                ReportPropertyChanging("DateClientApproved");
                _DateClientApproved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateClientApproved");
                OnDateClientApprovedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateClientApproved;
        partial void OnDateClientApprovedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateClientApprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientApprovedBy
        {
            get
            {
                return _ClientApprovedBy;
            }
            set
            {
                OnClientApprovedByChanging(value);
                ReportPropertyChanging("ClientApprovedBy");
                _ClientApprovedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientApprovedBy");
                OnClientApprovedByChanged();
            }
        }
        private global::System.String _ClientApprovedBy;
        partial void OnClientApprovedByChanging(global::System.String value);
        partial void OnClientApprovedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Approved
        {
            get
            {
                return _Approved;
            }
            set
            {
                OnApprovedChanging(value);
                ReportPropertyChanging("Approved");
                _Approved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Approved");
                OnApprovedChanged();
            }
        }
        private global::System.Boolean _Approved;
        partial void OnApprovedChanging(global::System.Boolean value);
        partial void OnApprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateApproved
        {
            get
            {
                return _DateApproved;
            }
            set
            {
                OnDateApprovedChanging(value);
                ReportPropertyChanging("DateApproved");
                _DateApproved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateApproved");
                OnDateApprovedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateApproved;
        partial void OnDateApprovedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateApprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApprovedBy
        {
            get
            {
                return _ApprovedBy;
            }
            set
            {
                OnApprovedByChanging(value);
                ReportPropertyChanging("ApprovedBy");
                _ApprovedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApprovedBy");
                OnApprovedByChanged();
            }
        }
        private global::System.String _ApprovedBy;
        partial void OnApprovedByChanging(global::System.String value);
        partial void OnApprovedByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TugboatDBModel", "FK_ClientWeek_Client", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("TugboatDBModel.FK_ClientWeek_Client", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("TugboatDBModel.FK_ClientWeek_Client", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("TugboatDBModel.FK_ClientWeek_Client", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("TugboatDBModel.FK_ClientWeek_Client", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TugboatDBModel", "FK_ClientWeek_Week", "Week")]
        public Week Week
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Week>("TugboatDBModel.FK_ClientWeek_Week", "Week").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Week>("TugboatDBModel.FK_ClientWeek_Week", "Week").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Week> WeekReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Week>("TugboatDBModel.FK_ClientWeek_Week", "Week");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Week>("TugboatDBModel.FK_ClientWeek_Week", "Week", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TugboatDBModel", "FK_Time_ClientWeek", "Time")]
        public EntityCollection<Time> Times
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Time>("TugboatDBModel.FK_Time_ClientWeek", "Time");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Time>("TugboatDBModel.FK_Time_ClientWeek", "Time", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TugboatDBModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        /// <param name="studentGuid">Initial value of the StudentGuid property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="dateModified">Initial value of the DateModified property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="modifiedBy">Initial value of the ModifiedBy property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        public static Student CreateStudent(global::System.Int32 studentId, global::System.Guid studentGuid, global::System.String firstName, global::System.String lastName, global::System.DateTime dateCreated, global::System.DateTime dateModified, global::System.String createdBy, global::System.String modifiedBy, global::System.Boolean active)
        {
            Student student = new Student();
            student.StudentId = studentId;
            student.StudentGuid = studentGuid;
            student.FirstName = firstName;
            student.LastName = lastName;
            student.DateCreated = dateCreated;
            student.DateModified = dateModified;
            student.CreatedBy = createdBy;
            student.ModifiedBy = modifiedBy;
            student.Active = active;
            return student;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                if (_StudentId != value)
                {
                    OnStudentIdChanging(value);
                    ReportPropertyChanging("StudentId");
                    _StudentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StudentId");
                    OnStudentIdChanged();
                }
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid StudentGuid
        {
            get
            {
                return _StudentGuid;
            }
            set
            {
                OnStudentGuidChanging(value);
                ReportPropertyChanging("StudentGuid");
                _StudentGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentGuid");
                OnStudentGuidChanged();
            }
        }
        private global::System.Guid _StudentGuid;
        partial void OnStudentGuidChanging(global::System.Guid value);
        partial void OnStudentGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PreviousName
        {
            get
            {
                return _PreviousName;
            }
            set
            {
                OnPreviousNameChanging(value);
                ReportPropertyChanging("PreviousName");
                _PreviousName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PreviousName");
                OnPreviousNameChanged();
            }
        }
        private global::System.String _PreviousName;
        partial void OnPreviousNameChanging(global::System.String value);
        partial void OnPreviousNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] SSN
        {
            get
            {
                return StructuralObject.GetValidValue(_SSN);
            }
            set
            {
                OnSSNChanging(value);
                ReportPropertyChanging("SSN");
                _SSN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SSN");
                OnSSNChanged();
            }
        }
        private global::System.Byte[] _SSN;
        partial void OnSSNChanging(global::System.Byte[] value);
        partial void OnSSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastFour
        {
            get
            {
                return _LastFour;
            }
            set
            {
                OnLastFourChanging(value);
                ReportPropertyChanging("LastFour");
                _LastFour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastFour");
                OnLastFourChanged();
            }
        }
        private global::System.String _LastFour;
        partial void OnLastFourChanging(global::System.String value);
        partial void OnLastFourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StudentStatus
        {
            get
            {
                return _StudentStatus;
            }
            set
            {
                OnStudentStatusChanging(value);
                ReportPropertyChanging("StudentStatus");
                _StudentStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentStatus");
                OnStudentStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _StudentStatus;
        partial void OnStudentStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStudentStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TugboatDBModel", "FK_Time_Student", "Time")]
        public EntityCollection<Time> Times
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Time>("TugboatDBModel.FK_Time_Student", "Time");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Time>("TugboatDBModel.FK_Time_Student", "Time", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TugboatDBModel", Name="Time")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Time : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Time object.
        /// </summary>
        /// <param name="timeId">Initial value of the TimeId property.</param>
        /// <param name="timeGuid">Initial value of the TimeGuid property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="dateModified">Initial value of the DateModified property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="modifiedBy">Initial value of the ModifiedBy property.</param>
        /// <param name="timeDate">Initial value of the TimeDate property.</param>
        /// <param name="clientWeekId">Initial value of the ClientWeekId property.</param>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        /// <param name="hoursWorked">Initial value of the HoursWorked property.</param>
        /// <param name="payRate">Initial value of the PayRate property.</param>
        public static Time CreateTime(global::System.Int32 timeId, global::System.Guid timeGuid, global::System.DateTime dateCreated, global::System.DateTime dateModified, global::System.String createdBy, global::System.String modifiedBy, global::System.DateTime timeDate, global::System.Int32 clientWeekId, global::System.Int32 studentId, global::System.Decimal hoursWorked, global::System.Decimal payRate)
        {
            Time time = new Time();
            time.TimeId = timeId;
            time.TimeGuid = timeGuid;
            time.DateCreated = dateCreated;
            time.DateModified = dateModified;
            time.CreatedBy = createdBy;
            time.ModifiedBy = modifiedBy;
            time.TimeDate = timeDate;
            time.ClientWeekId = clientWeekId;
            time.StudentId = studentId;
            time.HoursWorked = hoursWorked;
            time.PayRate = payRate;
            return time;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeId
        {
            get
            {
                return _TimeId;
            }
            set
            {
                if (_TimeId != value)
                {
                    OnTimeIdChanging(value);
                    ReportPropertyChanging("TimeId");
                    _TimeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TimeId");
                    OnTimeIdChanged();
                }
            }
        }
        private global::System.Int32 _TimeId;
        partial void OnTimeIdChanging(global::System.Int32 value);
        partial void OnTimeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TimeGuid
        {
            get
            {
                return _TimeGuid;
            }
            set
            {
                OnTimeGuidChanging(value);
                ReportPropertyChanging("TimeGuid");
                _TimeGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeGuid");
                OnTimeGuidChanged();
            }
        }
        private global::System.Guid _TimeGuid;
        partial void OnTimeGuidChanging(global::System.Guid value);
        partial void OnTimeGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimeDate
        {
            get
            {
                return _TimeDate;
            }
            set
            {
                OnTimeDateChanging(value);
                ReportPropertyChanging("TimeDate");
                _TimeDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeDate");
                OnTimeDateChanged();
            }
        }
        private global::System.DateTime _TimeDate;
        partial void OnTimeDateChanging(global::System.DateTime value);
        partial void OnTimeDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientWeekId
        {
            get
            {
                return _ClientWeekId;
            }
            set
            {
                OnClientWeekIdChanging(value);
                ReportPropertyChanging("ClientWeekId");
                _ClientWeekId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientWeekId");
                OnClientWeekIdChanged();
            }
        }
        private global::System.Int32 _ClientWeekId;
        partial void OnClientWeekIdChanging(global::System.Int32 value);
        partial void OnClientWeekIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                OnStudentIdChanging(value);
                ReportPropertyChanging("StudentId");
                _StudentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentId");
                OnStudentIdChanged();
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal HoursWorked
        {
            get
            {
                return _HoursWorked;
            }
            set
            {
                OnHoursWorkedChanging(value);
                ReportPropertyChanging("HoursWorked");
                _HoursWorked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HoursWorked");
                OnHoursWorkedChanged();
            }
        }
        private global::System.Decimal _HoursWorked;
        partial void OnHoursWorkedChanging(global::System.Decimal value);
        partial void OnHoursWorkedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PayRate
        {
            get
            {
                return _PayRate;
            }
            set
            {
                OnPayRateChanging(value);
                ReportPropertyChanging("PayRate");
                _PayRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayRate");
                OnPayRateChanged();
            }
        }
        private global::System.Decimal _PayRate;
        partial void OnPayRateChanging(global::System.Decimal value);
        partial void OnPayRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DayOfWeek
        {
            get
            {
                return _DayOfWeek;
            }
            set
            {
                OnDayOfWeekChanging(value);
                ReportPropertyChanging("DayOfWeek");
                _DayOfWeek = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayOfWeek");
                OnDayOfWeekChanged();
            }
        }
        private Nullable<global::System.Int32> _DayOfWeek;
        partial void OnDayOfWeekChanging(Nullable<global::System.Int32> value);
        partial void OnDayOfWeekChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TugboatDBModel", "FK_Time_Student", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("TugboatDBModel.FK_Time_Student", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("TugboatDBModel.FK_Time_Student", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("TugboatDBModel.FK_Time_Student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("TugboatDBModel.FK_Time_Student", "Student", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TugboatDBModel", "FK_Time_ClientWeek", "ClientWeek")]
        public ClientWeek ClientWeek
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientWeek>("TugboatDBModel.FK_Time_ClientWeek", "ClientWeek").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientWeek>("TugboatDBModel.FK_Time_ClientWeek", "ClientWeek").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ClientWeek> ClientWeekReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientWeek>("TugboatDBModel.FK_Time_ClientWeek", "ClientWeek");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ClientWeek>("TugboatDBModel.FK_Time_ClientWeek", "ClientWeek", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TugboatDBModel", Name="Week")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Week : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Week object.
        /// </summary>
        /// <param name="weekId">Initial value of the WeekId property.</param>
        /// <param name="weekGuid">Initial value of the WeekGuid property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="dateModified">Initial value of the DateModified property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="modifiedBy">Initial value of the ModifiedBy property.</param>
        /// <param name="weekEnding">Initial value of the WeekEnding property.</param>
        public static Week CreateWeek(global::System.Int32 weekId, global::System.Guid weekGuid, global::System.DateTime dateCreated, global::System.DateTime dateModified, global::System.String createdBy, global::System.String modifiedBy, global::System.DateTime weekEnding)
        {
            Week week = new Week();
            week.WeekId = weekId;
            week.WeekGuid = weekGuid;
            week.DateCreated = dateCreated;
            week.DateModified = dateModified;
            week.CreatedBy = createdBy;
            week.ModifiedBy = modifiedBy;
            week.WeekEnding = weekEnding;
            return week;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WeekId
        {
            get
            {
                return _WeekId;
            }
            set
            {
                if (_WeekId != value)
                {
                    OnWeekIdChanging(value);
                    ReportPropertyChanging("WeekId");
                    _WeekId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WeekId");
                    OnWeekIdChanged();
                }
            }
        }
        private global::System.Int32 _WeekId;
        partial void OnWeekIdChanging(global::System.Int32 value);
        partial void OnWeekIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid WeekGuid
        {
            get
            {
                return _WeekGuid;
            }
            set
            {
                OnWeekGuidChanging(value);
                ReportPropertyChanging("WeekGuid");
                _WeekGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WeekGuid");
                OnWeekGuidChanged();
            }
        }
        private global::System.Guid _WeekGuid;
        partial void OnWeekGuidChanging(global::System.Guid value);
        partial void OnWeekGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime WeekEnding
        {
            get
            {
                return _WeekEnding;
            }
            set
            {
                OnWeekEndingChanging(value);
                ReportPropertyChanging("WeekEnding");
                _WeekEnding = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WeekEnding");
                OnWeekEndingChanged();
            }
        }
        private global::System.DateTime _WeekEnding;
        partial void OnWeekEndingChanging(global::System.DateTime value);
        partial void OnWeekEndingChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TugboatDBModel", "FK_ClientWeek_Week", "ClientWeek")]
        public EntityCollection<ClientWeek> ClientWeeks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClientWeek>("TugboatDBModel.FK_ClientWeek_Week", "ClientWeek");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClientWeek>("TugboatDBModel.FK_ClientWeek_Week", "ClientWeek", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
